### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by 66demon666**
Translate the app to Russian language

### CODE REVIEW

**Comment by keepalivedev** [comment]
Thanks for the PR!  Could you also create a new fastlane metadata folder at fastlane\metadata\android\ru-RU\ and include translations for the short and full descriptions?

**Comment by 66demon666** [comment]
completed

**Comment by keepalivedev** [comment]
You can remove the screenshots, I'll generate them after the merge.  Also can you make the short_description.txt less than 80 characters?

**Comment by 66demon666** [comment]
completed

**Pull request merged**
